nodeLinker: node-modules

npmRegistries:
  //npm.greensock.com:
    npmAlwaysAuth: true
    npmAuthToken: "${GSAP_TOKEN:-}"

npmScopes:
  gsap:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.greensock.com"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
