nodeLinker: node-modules

npmRegistries:
  //npm.greensock.com:
    npmAlwaysAuth: true
    npmAuthToken: "${GSAP_TOKEN:-}"

npmScopes:
  gsap:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.greensock.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
