export const particleTypes = [
  {
    particle_size: 0.01,
    particle_size_frequency: 1.188,
    particle_size_dispersion: 0.3,
    rotation_dispersion: 0.1,
    time_scale: 0.01,
    twist_speed: 0,
    twist_frequency: 3,
    twist_dispersion: 0.1,
    twist_dispersion_frequency: 2,
    twist_amplitude: 5,
    rotation_speed: 0,
    frequency: 0,
    amplitude: 0.346,
    offset: 0,
    opacity: 0.5,
    cone_shape: 0,
    color: "pink",
    instance_count: 100,
    min_radius: 2,
    max_radius: 5,
  },
  {
    particle_size: 0.03,
    particle_size_frequency: 0.658,
    particle_size_dispersion: 0.197,
    time_scale: 0.098,
    twist_speed: 1.76,
    twist_dispersion: 0.1,
    twist_dispersion_frequency: 1.196,
    twist_frequency: 0.2136,
    twist_amplitude: 0.2,
    rotation_speed: 0.1,
    rotation_dispersion: 0.168,
    frequency: 0.69,
    amplitude: 0.092,
    offset: 0.6,
    opacity: 1,
    cone_shape: 1,
    color: "#a78bfa",
    instance_count: 1e4,
    min_radius: 1.5,
    max_radius: 10,
  },
  {
    particle_size: 0.0184,
    particle_size_frequency: 1.62,
    particle_size_dispersion: 0.144,
    time_scale: 0.147,
    twist_speed: 0.12,
    twist_dispersion: 1.3,
    twist_dispersion_frequency: 0.72,
    twist_frequency: 0.183,
    twist_amplitude: 0,
    rotation_speed: 0.12,
    rotation_dispersion: 0.01,
    frequency: 1.37,
    amplitude: 0.188,
    offset: 2.22,
    opacity: 0.5,
    cone_shape: 1,
    color: "#06b6d4",
    instance_count: 2e4,
    min_radius: 1.5,
    max_radius: 10,
  },
];
